All data pulled from: https://www.masseyratings.com/data

In [72]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import numpy as np
import re

In [73]:
master_df = pd.DataFrame(columns=['Team1', 'Team1_Score', 'Team2', 'Team2_Score', 'Winner', 'Year'])

# Iterate through files and cleanup
for i in range(2013, 2019):
    
    # Read in file
    year = str(i)
    test = pd.read_fwf('unclean_tournament_results/' + year + '_results.csv', header=None)

    # Drop unneeded columns
    test = test[[1, 2, 3, 4]]

    # Rename columns
    test.rename(columns={1: 'Team1', 2: 'Team1_Score', 3: 'Team2', 4: 'Team2_Score'}, inplace=True)

    # Drop @ symbol
    test['Team1'] = test['Team1'].str.replace(r'@', '')
    test['Team2'] = test['Team2'].str.replace(r'@', '')

    # Strip whitespace
    test['Team1'] = test['Team1'].str.strip()
    test['Team2'] = test['Team2'].str.strip()

    # Determine winner
    test['Winner'] = ['Team1' if int(x) > int(y) else 'Team2'\
                        for x, y in zip(test['Team1_Score'], test['Team2_Score'])]

    # Create Year Column
    test['Year'] = year
    
    master_df = pd.concat([master_df, test], ignore_index=True)
    
master_df.to_csv('tournament_results/2013_2018.csv', index=False)
master_df

              Team1 Team1_Score           Team2 Team2_Score Winner  Year
0            NC A&T          73         Liberty          72  Team1  2013
1      St Mary's CA          67            MTSU          54  Team1  2013
2          Maryland          86         Niagara          70  Team1  2013
3         St John's          63  St Joseph's PA          61  Team1  2013
4    Louisiana Tech          71      Florida St          66  Team1  2013
5     Robert Morris          59        Kentucky          57  Team1  2013
6          Virginia          67      Norfolk St          56  Team1  2013
7           Alabama          62    Northeastern          43  Team1  2013
8            Denver          61            Ohio          57  Team1  2013
9               BYU          90      Washington          79  Team1  2013
10         Stanford          58       SF Austin          57  Team1  2013
11     George Mason          78  Col Charleston          77  Team1  2013
12          Wyoming          67          Lehigh          66  Team1  2013
13      Santa Clara          77         Vermont          67  Team1  2013
14            Rider          63        Hartford          54  Team1  2013
15    East Carolina          66     Savannah St          65  Team1  2013
16       E Kentucky          69    Gardner Webb          62  Team1  2013
17    Youngstown St          99         Oakland          87  Team1  2013
18        Loyola MD          70     Boston Univ          63  Team1  2013
19       Evansville          84    Tennessee St          72  Team1  2013
20    James Madison          68    LIU Brooklyn          55  Team1  2013
21         La Salle          80        Boise St          71  Team1  2013
22             Iowa          68      Indiana St          52  Team1  2013
23      Stony Brook          71   Massachusetts          58  Team1  2013
24       Providence          75       Charlotte          66  Team1  2013
25           Mercer          75       Tennessee          67  Team1  2013
26           Baylor         112   Long Beach St          66  Team1  2013
27    Southern Miss          78   Charleston So          71  Team1  2013
28       Arizona St          83         Detroit          68  Team1  2013
29           Purdue          81      W Illinois          67  Team1  2013
..              ...         ...             ...         ...    ...   ...
819     North Texas          90  Jacksonville S          68  Team1  2018
820             WKU          92     Oklahoma St          84  Team1  2018
821            Utah          67    St Mary's CA          58  Team1  2018
822  Loyola-Chicago          69          Nevada          68  Team1  2018
823        Michigan          99       Texas A&M          72  Team1  2018
824       Kansas St          61        Kentucky          58  Team1  2018
825      Florida St          75         Gonzaga          60  Team1  2018
826  Sam Houston St          76  UT San Antonio          69  Team1  2018
827   San Francisco          65        Campbell          62  Team1  2018
828          Kansas          80         Clemson          76  Team1  2018
829       Villanova          90   West Virginia          78  Team1  2018
830            Duke          69        Syracuse          65  Team1  2018
831      Texas Tech          78          Purdue          65  Team1  2018
832         Liberty          84      C Michigan          71  Team1  2018
833  Loyola-Chicago          78       Kansas St          62  Team1  2018
834        Michigan          58      Florida St          54  Team1  2018
835       Villanova          71      Texas Tech          59  Team1  2018
836          Kansas          85            Duke          81  Team1  2018
837   San Francisco          72     North Texas          62  Team1  2018
838            Utah          69             WKU          64  Team1  2018
839         Penn St          75  Mississippi St          60  Team1  2018
840      IL Chicago          67         Liberty          51  Team1  2018
841     North Texas          69   San Francisco          55  Team1  2018
842      N Colorado          99  Sam Houston St          80  Team1  2018
843         Penn St          82            Utah          66  Team1  2018
844     North Texas          88   San Francisco          77  Team1  2018
845      N Colorado          76      IL Chicago          71  Team1  2018
846       Villanova          95          Kansas          79  Team1  2018
847        Michigan          69  Loyola-Chicago          57  Team1  2018
848       Villanova          79        Michigan          62  Team1  2018

[849 rows x 6 columns]